version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: practice_panther_db
    ports:
    # Map port 5432 inside the container to port 5433 on the host machine (Choose different ports if needed)
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
